# Generated by Django 4.2.16 on 2024-11-24 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('fio', models.CharField(max_length=100, verbose_name='ФИО клиента')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес клиента')),
                ('customer_phone', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Телефон должен содержать только цифры и может начинаться с +', regex='^\\+?[0-9]*$')], verbose_name='Телефон клиента')),
                ('status', models.CharField(choices=[('активный', 'Активный'), ('ушедший', 'Ушедший')], max_length=20, verbose_name='Статус клиента')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('container_id', models.AutoField(primary_key=True, serialize=False)),
                ('container_volume', models.IntegerField(verbose_name='Объем тары')),
                ('container_type', models.CharField(max_length=100, verbose_name='Тип тары')),
                ('container_availability', models.BooleanField(default=True, verbose_name='Доступность тары')),
            ],
            options={
                'verbose_name': 'тара',
                'verbose_name_plural': 'Тары',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_fio', models.CharField(max_length=100, verbose_name='ФИО сотрудника')),
                ('employee_position', models.CharField(max_length=50, verbose_name='Должность сотрудника')),
                ('employee_schedule', models.CharField(max_length=255, verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('delivery_datetime', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата и время доставки')),
                ('order_status', models.CharField(choices=[('новый', 'Новый'), ('завершенный', 'Завершенный'), ('отмененный', 'Отмененный')], max_length=20, verbose_name='Статус заказа')),
                ('order_type', models.CharField(choices=[('разовый', 'Разовый'), ('абонемент на 30 дней', 'Абонемент на 30 дней'), ('абонемент на полгода', 'Абонемент на полгода'), ('абонемент на год', 'Абонемент на год')], max_length=50, verbose_name='Тип заказа')),
                ('container_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.containers', verbose_name='Тара')),
                ('customer_phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.clients', verbose_name='Телефон клиента')),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
