# Generated by Django 4.2.16 on 2024-11-24 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='customer_phone',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='\n                Телефон должен содержать только цифры и может начинаться с +', regex='^\\+?[0-9]*$')], verbose_name='Телефон клиента'),
        ),
    ]
