# Generated by Django 4.2.16 on 2024-12-05 17:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='address',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Адрес должен содержать только буквы и пробелы.', regex='^[А-Яа-яЁё\\s]+$')], verbose_name='Адрес клиента'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='fio',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ФИО должно содержать только буквы и пробелы.', regex='^[А-Яа-яЁё\\s]+$')], verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='container_type',
            field=models.CharField(choices=[('пластиковая бутылка', 'Пластиковая бутылка'), ('стеклянная бутылка', 'Стеклянная бутылка'), ('канистра', 'Канистра'), ('ёмкость для куллера', 'Ёмкость для куллера')], max_length=100, verbose_name='Тип тары'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_fio',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ФИО должно содержать только буквы и пробелы.', regex='^[А-Яа-яЁё\\s]+$')], verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_position',
            field=models.CharField(choices=[('менеджер', 'Менеджер'), ('курьер', 'Курьер'), ('оператор', 'Оператор')], max_length=50, verbose_name='Должность сотрудника'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_schedule',
            field=models.CharField(choices=[('Пн-Пт, 9:00-18:00', 'Пн-Пт, 9:00-18:00'), ('Пн-Вс, 9:00-22:00', 'Пн-Вс, 9:00-22:00'), ('Пн-Вс, 8:00-20:00', 'Пн-Вс, 8:00-20:00')], max_length=255, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время доставки'),
        ),
    ]
