# Generated by Django 4.2.16 on 2024-11-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='container_type',
            field=models.CharField(choices=[('пластиковая бутылка', 'Пластиковая бутылка'), ('стеклянная бутылка', 'Стеклянная бутылка'), ('канистра', 'Канистра'), ('ёмкость для куллера', 'Ёмкость для куллера')], max_length=100, verbose_name='Тип тары'),
        ),
    ]
