# Generated by Django 4.2.16 on 2024-11-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_clients_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_datetime',
            field=models.DateTimeField(verbose_name='Дата и время доставки'),
        ),
    ]
