# Generated by Django 4.2.16 on 2024-11-27 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_employees_employee_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время доставки'),
        ),
    ]
