# Generated by Django 4.2.16 on 2024-11-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_orders_delivery_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.clients', verbose_name='Телефон клиента'),
        ),
    ]
