# Generated by Django 4.2.16 on 2024-11-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_orders_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.clients', verbose_name='Телефон клиента'),
        ),
    ]
